import { StyleSheet, Dimensions } from 'react-native';
import { COLORS } from '../../constants/colors';

const { width } = Dimensions.get('window');

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f8f6f3' },

  // Updated Header Style to match Figma MoreScreen
  header: {
    backgroundColor: COLORS.navy,
    height: 180,
    width: '100%',
    overflow: 'hidden',
    position: 'relative',
  },
  headerCircle1: {
    position: 'absolute',
    width: 160,
    height: 160,
    borderRadius: 80,
    backgroundColor: COLORS.gold,
    opacity: 0.1,
    top: -48,
    right: -20,
  },
  headerCircle2: {
    position: 'absolute',
    width: 96,
    height: 96,
    borderRadius: 48,
    backgroundColor: COLORS.gold,
    opacity: 0.05,
    bottom: 20,
    left: -24,
  },
  headerContent: {
    paddingTop: 60,
    paddingHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    zIndex: 1,
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.1)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: COLORS.white,
  },

  // Hero Section with New Logo
  hero: {
    alignItems: 'center',
    paddingHorizontal: 24,
    marginTop: -40,
    marginBottom: 24,
    zIndex: 2,
  },
  logoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.white,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 20,
    shadowColor: COLORS.navy,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.1,
    shadowRadius: 20,
    elevation: 10,
    marginBottom: 20,
    gap: 12,
  },
  logoBox: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: COLORS.gold,
    justifyContent: 'center',
    alignItems: 'center',
  },
  logoText: {
    fontSize: 20,
    fontWeight: '800',
    color: COLORS.navy,
    letterSpacing: -0.5,
  },
  heroTitle: {
    fontSize: 26,
    fontWeight: 'bold',
    color: COLORS.navy,
    textAlign: 'center',
    marginBottom: 12,
  },
  heroSub: {
    fontSize: 15,
    color: COLORS.gray600,
    textAlign: 'center',
    lineHeight: 24,
  },

  // Stats Card (Matching MoreScreen Stats)
  statsCard: {
    backgroundColor: COLORS.white,
    marginHorizontal: 20,
    borderRadius: 16,
    flexDirection: 'row',
    paddingVertical: 20,
    shadowColor: COLORS.navy,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 24,
    elevation: 4,
    marginBottom: 32,
  },
  statItem: { flex: 1, alignItems: 'center' },
  statValue: { fontSize: 20, fontWeight: 'bold', color: COLORS.navy },
  statLabel: { fontSize: 12, color: COLORS.gray400, marginTop: 4 },
  statDivider: { width: 1, backgroundColor: '#f0ede8', height: '60%', alignSelf: 'center' },

  section: { paddingHorizontal: 20, marginBottom: 32 },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: COLORS.navy,
    marginBottom: 20,
    letterSpacing: 0.5,
  },

  offersGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
  offerCard: {
    width: (width - 52) / 2,
    backgroundColor: COLORS.white,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1.5,
    borderColor: '#f0ede8',
  },
  offerIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: 'rgba(212,165,116,0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  offerTitle: { fontSize: 14, fontWeight: 'bold', color: COLORS.navy, marginBottom: 6 },
  offerDesc: { fontSize: 12, color: COLORS.gray500, lineHeight: 18 },

  experienceImg: {
    width: '100%',
    height: 220,
    borderRadius: 20,
    marginBottom: 20,
  },
  experienceTitle: { fontSize: 20, fontWeight: 'bold', color: COLORS.navy, marginBottom: 12 },
  experienceText: { fontSize: 15, color: COLORS.gray600, lineHeight: 24, marginBottom: 12 },

  reviewCard: {
    backgroundColor: COLORS.white,
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    borderWidth: 1.5,
    borderColor: '#f0ede8',
  },
  starsRow: { flexDirection: 'row', gap: 4, marginBottom: 12 },
  reviewText: {
    fontSize: 14,
    color: COLORS.gray700,
    lineHeight: 22,
    fontStyle: 'italic',
    marginBottom: 12,
  },
  reviewAuthor: { fontSize: 14, fontWeight: 'bold', color: COLORS.navy },
});
