import { StyleSheet, Platform } from 'react-native';
import { COLORS } from '../../constants/colors';

export default StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: '#f8f6f3',
  },
  scrollContainer: {
    flex: 1,
  },
  imageContainer: {
    position: 'relative',
    height: 300,
  },
  image: {
    height: 300,
    resizeMode: 'cover',
  },
  imageOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 100,
    backgroundColor: 'rgba(0,0,0,0.3)',
  },
  backBtn: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 56 : 40,
    left: 20,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.9)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  topRightBtns: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 56 : 40,
    right: 20,
    flexDirection: 'row',
    gap: 8,
  },
  iconBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.9)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  dotsRow: {
    position: 'absolute',
    bottom: 20,
    alignSelf: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  dot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: 'rgba(255,255,255,0.6)',
  },
  dotActive: {
    backgroundColor: COLORS.gold,
    width: 20,
  },
  block: {
    backgroundColor: COLORS.white,
    padding: 20,
    marginBottom: 8,
  },
  badge: {
    backgroundColor: 'rgba(212,165,116,0.13)',
    alignSelf: 'flex-start',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    marginBottom: 8,
  },
  badgeText: {
    color: COLORS.gold,
    fontSize: 12,
    fontWeight: '600',
    letterSpacing: 0.6,
  },
  titleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  title: {
    fontSize: 22,
    fontWeight: 'bold',
    color: COLORS.navy,
    flex: 1,
    marginRight: 10,
  },
  priceContainer: {
    alignItems: 'flex-end',
  },
  priceText: {
    fontSize: 24,
    fontWeight: 'bold',
    color: COLORS.gold,
  },
  perNightText: {
    fontSize: 12,
    color: COLORS.gray400,
    marginTop: -2,
  },
  ratingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
  },
  stars: {
    flexDirection: 'row',
    gap: 2,
    marginRight: 6,
  },
  ratingScore: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.navy,
    marginRight: 6,
  },
  reviewCount: {
    fontSize: 14,
    color: COLORS.gray400,
  },
  divider: {
    height: 1,
    backgroundColor: COLORS.gray100,
    marginVertical: 16,
  },
  specsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  specItem: {
    alignItems: 'center',
    flex: 1,
  },
  specLabel: {
    fontSize: 12,
    color: COLORS.gray400,
    marginBottom: 4,
  },
  specValue: {
    fontSize: 12,
    fontWeight: '600',
    color: COLORS.navy,
    textAlign: 'center',
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: COLORS.navy,
    marginBottom: 12,
  },
  description: {
    fontSize: 14,
    color: '#4a5565',
    lineHeight: 22,
  },
  amenitiesWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  amenityTag: {
    backgroundColor: '#f8f6f3',
    borderColor: '#ede9e4',
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 14,
  },
  amenityTagText: {
    fontSize: 12,
    fontWeight: '500',
    color: COLORS.navy,
  },
  dateRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 12,
  },
  dateBox: {
    flex: 1,
    borderWidth: 1,
    borderColor: COLORS.gray200,
    borderRadius: 12,
    padding: 12,
    backgroundColor: COLORS.white,
  },
  dateLabel: {
    fontSize: 12,
    color: COLORS.gray400,
    marginBottom: 4,
  },
  dateValue: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.navy,
  },
  datePlaceholder: {
    fontSize: 14,
    color: COLORS.gray300,
  },
  guestSelector: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: COLORS.gray200,
    borderRadius: 12,
    marginBottom: 12,
  },
  guestSelectorLabel: {
    fontSize: 14,
    fontWeight: '500',
    color: COLORS.navy,
  },
  guestControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  guestBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: COLORS.gray100,
    alignItems: 'center',
    justifyContent: 'center',
  },
  guestBtnDisabled: {
    opacity: 0.5,
  },
  guestCount: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.navy,
    minWidth: 20,
    textAlign: 'center',
  },
  conflictWarning: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: COLORS.redLight,
    padding: 12,
    borderRadius: 8,
    marginBottom: 12,
  },
  conflictText: {
    fontSize: 13,
    color: COLORS.red,
    fontWeight: '500',
  },
  summaryBox: {
    backgroundColor: '#f8f6f3',
    borderRadius: 12,
    padding: 16,
    marginTop: 8,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  summaryLabel: {
    fontSize: 13,
    color: COLORS.gray500,
  },
  summaryValue: {
    fontSize: 13,
    color: COLORS.navy,
    fontWeight: '500',
  },
  summaryTotal: {
    fontSize: 16,
    color: COLORS.gold,
    fontWeight: 'bold',
  },
  reviewsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  reviewScoreBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  reviewScoreText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: COLORS.navy,
  },
  reviewEmpty: {
    color: COLORS.gray400,
    fontSize: 13,
    paddingVertical: 8,
  },
  reviewItem: {
    paddingBottom: 16,
    marginBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.gray100,
  },
  reviewUserRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  avatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: COLORS.navy,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  avatarText: {
    color: COLORS.white,
    fontSize: 14,
    fontWeight: 'bold',
  },
  userInfo: {
    flex: 1,
  },
  reviewUserName: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.navy,
  },
  reviewDate: {
    fontSize: 12,
    color: COLORS.gray400,
    marginTop: 2,
  },
  reviewItemStars: {
    flexDirection: 'row',
    gap: 2,
  },
  reviewText: {
    fontSize: 14,
    color: '#4a5565',
    lineHeight: 22,
  },
  bottomBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: COLORS.white,
    borderTopWidth: 1,
    borderTopColor: COLORS.gray100,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: Platform.OS === 'ios' ? 32 : 20,
    shadowColor: '#0a1e3d',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.06,
    shadowRadius: 20,
    elevation: 8,
  },
  bottomBarLabel: {
    fontSize: 12,
    color: COLORS.gray400,
    marginBottom: 2,
  },
  bottomBarPrice: {
    fontSize: 22,
    fontWeight: 'bold',
    color: COLORS.navy,
  },
  bottomBarPerNight: {
    fontSize: 14,
    fontWeight: 'normal',
    color: COLORS.gray400,
  },
  bookBtn: {
    backgroundColor: COLORS.gold,
    height: 50,
    borderRadius: 16,
    paddingHorizontal: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bookBtnDisabled: {
    backgroundColor: COLORS.gray300,
  },
  bookBtnText: {
    color: COLORS.white,
    fontSize: 15,
    fontWeight: '600',
  },
  pickerHeader: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.gray100,
    backgroundColor: COLORS.white,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  pickerTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: COLORS.navy,
  },
  pickerDone: {
    fontSize: 16,
    fontWeight: 'bold',
    color: COLORS.gold,
  },
});
