import { StyleSheet } from 'react-native';
import { COLORS } from '../../constants/colors';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f8f6f3' },

  // Unified Header Style
  header: {
    backgroundColor: COLORS.navy,
    height: 180,
    width: '100%',
    overflow: 'hidden',
    position: 'relative',
  },
  headerCircle1: {
    position: 'absolute',
    width: 160,
    height: 160,
    borderRadius: 80,
    backgroundColor: COLORS.gold,
    opacity: 0.1,
    top: -48,
    right: -20,
  },
  headerCircle2: {
    position: 'absolute',
    width: 96,
    height: 96,
    borderRadius: 48,
    backgroundColor: COLORS.gold,
    opacity: 0.05,
    bottom: 20,
    left: -24,
  },
  headerContent: {
    paddingTop: 60,
    paddingHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    zIndex: 1,
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.1)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitleContainer: { flex: 1 },
  headerTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: COLORS.white,
  },
  headerSubtitle: {
    fontSize: 13,
    color: 'rgba(255,255,255,0.6)',
    marginTop: 2,
  },

  body: {
    padding: 20,
    marginTop: -20,
    backgroundColor: '#f8f6f3',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
  },
  intro: {
    fontSize: 14,
    color: COLORS.gray600,
    textAlign: 'center',
    marginBottom: 24,
    lineHeight: 22,
    backgroundColor: 'rgba(212,165,116,0.08)',
    padding: 16,
    borderRadius: 16,
  },
  introLink: { color: COLORS.gold, fontWeight: '700' },

  item: {
    backgroundColor: COLORS.white,
    borderRadius: 18,
    marginBottom: 12,
    overflow: 'hidden',
    borderWidth: 1.5,
    borderColor: '#f0ede8',
  },
  itemOpen: {
    borderColor: COLORS.gold,
    shadowColor: COLORS.gold,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 3,
  },
  questionRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 18,
    gap: 12,
  },
  questionLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    gap: 14,
  },
  qNumber: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: 'rgba(212,165,116,0.1)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  qNumberText: { fontSize: 14, fontWeight: 'bold', color: COLORS.gold },
  questionText: { flex: 1, fontSize: 15, fontWeight: '600', color: COLORS.navy, lineHeight: 22 },
  
  answerWrap: {
    paddingHorizontal: 18,
    paddingBottom: 20,
    paddingTop: 4,
    borderTopWidth: 1,
    borderTopColor: '#f0ede8',
    backgroundColor: 'rgba(212,165,116,0.03)',
  },
  answerText: { fontSize: 14, color: COLORS.gray600, lineHeight: 22 },
});
