import { StyleSheet } from 'react-native';
import { COLORS } from '../../constants/colors';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.navy },
  scroll: { flexGrow: 1 },
  top: { alignItems: 'center', paddingTop: 56, paddingBottom: 28 },
  backBtn: { position: 'absolute', top: 56, left: 20 },
  logoContainer: { width: 48, height: 48, borderRadius: 14, backgroundColor: COLORS.gold, justifyContent: 'center', alignItems: 'center', marginBottom: 12 },
  logoIcon: { fontSize: 20, color: COLORS.white },
  logo: { fontSize: 24, fontWeight: 'bold', color: COLORS.white, letterSpacing: 4 },
  tagline: { fontSize: 13, color: COLORS.gray400, marginTop: 4 },
  form: { backgroundColor: COLORS.white, borderTopLeftRadius: 32, borderTopRightRadius: 32, padding: 28, paddingBottom: 48, flex: 1 },
  formTitle: { fontSize: 24, fontWeight: 'bold', color: COLORS.navy, marginBottom: 4 },
  formSubtitle: { fontSize: 14, color: COLORS.gray500, marginBottom: 20 },
  nameRow: { flexDirection: 'row' },
  fieldGroup: { marginBottom: 14 },
  label: { fontSize: 13, fontWeight: '600', color: COLORS.gray700, marginBottom: 7 },
  inputWrap: { flexDirection: 'row', alignItems: 'center', borderWidth: 1.5, borderColor: COLORS.gray200, borderRadius: 12, backgroundColor: COLORS.gray100, paddingHorizontal: 12 },
  inputError: { borderColor: COLORS.red },
  input: { flex: 1, paddingVertical: 13, fontSize: 14, color: COLORS.gray900 },
  eyeBtn: { padding: 4 },
  errorText: { fontSize: 12, color: COLORS.red, marginTop: 5, marginLeft: 2 },
  button: { backgroundColor: COLORS.gold, padding: 15, borderRadius: 12, alignItems: 'center', marginTop: 8, marginBottom: 16, elevation: 2 },
  buttonDisabled: { opacity: 0.7 },
  buttonText: { color: COLORS.white, fontWeight: 'bold', fontSize: 16, letterSpacing: 0.5 },
  link: { alignItems: 'center' },
  linkText: { color: COLORS.gray500, fontSize: 14 },
  linkBold: { fontWeight: 'bold', color: COLORS.navy },
});