import { StyleSheet, Platform, Dimensions } from 'react-native';
import { COLORS } from '../../constants/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8F6F3',
  },
  header: {
    backgroundColor: COLORS.navy,
    paddingTop: 60,
    paddingBottom: 25,
    paddingHorizontal: 20,
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
  },
  headerTop: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  backButton: {
    padding: 5,
    marginRight: 10,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: COLORS.white,
  },
  progressContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
  },
  stepContainer: {
    alignItems: 'center',
  },
  stepCircleActive: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: COLORS.gold,
    justifyContent: 'center',
    alignItems: 'center',
  },
  stepCircleInactive: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: 'rgba(255,255,255,0.15)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  stepNumberText: {
    color: COLORS.white,
    fontSize: 12,
    fontWeight: '700',
  },
  stepText: {
    color: COLORS.white,
    fontSize: 12,
    marginTop: 4,
  },
  stepLineInactive: {
    flex: 1,
    height: 1,
    backgroundColor: 'rgba(255,255,255,0.15)',
    marginHorizontal: 8,
    marginTop: -16,
  },
  content: {
    flex: 1,
    padding: 20,
  },
  summaryCard: {
    backgroundColor: COLORS.white,
    borderRadius: 16,
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: COLORS.navy,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 12,
    elevation: 2,
    marginBottom: 20,
  },
  roomThumb: {
    width: 56,
    height: 56,
    borderRadius: 14,
  },
  roomInfo: {
    flex: 1,
    marginLeft: 12,
  },
  roomType: {
    fontSize: 12,
    color: COLORS.gold,
    marginBottom: 2,
  },
  roomName: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.navy,
    marginBottom: 2,
  },
  roomMeta: {
    fontSize: 12,
    color: COLORS.gray500,
  },
  priceInfo: {
    alignItems: 'flex-end',
  },
  priceText: {
    fontSize: 16,
    fontWeight: '700',
    color: COLORS.gold,
  },
  perNight: {
    fontSize: 12,
    color: COLORS.gray500,
  },
  formGroup: {
    marginBottom: 20,
  },
  label: {
    fontSize: 12,
    fontWeight: '600',
    color: COLORS.navy,
    marginBottom: 8,
    letterSpacing: 0.6,
  },
  dateInput: {
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 16,
    height: 52,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    shadowColor: COLORS.navy,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 1,
  },
  inputIcon: {
    marginRight: 12,
  },
  inputValue: {
    fontSize: 14,
    fontWeight: '500',
    color: COLORS.navy,
  },
  inputPlaceholder: {
    fontSize: 14,
    color: 'rgba(10, 30, 61, 0.4)',
  },
  guestSelector: {
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 16,
    height: 64,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    shadowColor: COLORS.navy,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 1,
  },
  guestBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#F3F4F6',
    justifyContent: 'center',
    alignItems: 'center',
  },
  guestBtnPlus: {
    backgroundColor: COLORS.gold,
  },
  guestBtnText: {
    fontSize: 20,
    fontWeight: '700',
    color: COLORS.navy,
  },
  guestCount: {
    flex: 1,
    textAlign: 'center',
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.navy,
  },
  maxCapacity: {
    fontSize: 12,
    color: COLORS.gray500,
    marginTop: 8,
    marginLeft: 4,
  },
  breakdownCard: {
    backgroundColor: 'rgba(10, 30, 61, 0.03)',
    borderWidth: 1,
    borderColor: 'rgba(10, 30, 61, 0.08)',
    borderRadius: 16,
    padding: 16,
    marginTop: 10,
  },
  breakdownTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.navy,
    marginBottom: 12,
  },
  breakdownRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  breakdownLabel: {
    fontSize: 14,
    color: '#6A7282',
  },
  breakdownValue: {
    fontSize: 14,
    color: '#6A7282',
  },
  totalLabel: {
    fontSize: 16,
    fontWeight: '700',
    color: COLORS.navy,
  },
  totalValue: {
    fontSize: 16,
    fontWeight: '700',
    color: COLORS.gold,
  },
  bottomBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: COLORS.white,
    paddingHorizontal: 20,
    paddingTop: 15,
    paddingBottom: Platform.OS === 'ios' ? 35 : 20,
    borderTopWidth: 1,
    borderTopColor: '#F0EDE8',
  },
  continueBtn: {
    backgroundColor: COLORS.gold,
    height: 56,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  continueBtnText: {
    color: COLORS.white,
    fontSize: 16,
    fontWeight: '600',
  },
  pickerOverlay: { 
    flex: 1, 
    justifyContent: 'flex-end', 
    backgroundColor: 'rgba(0,0,0,0.4)' 
  },
  pickerSheet: { 
    backgroundColor: COLORS.white, 
    borderTopLeftRadius: 24, 
    borderTopRightRadius: 24, 
    paddingBottom: 40, 
    alignItems: 'center' 
  },
  pickerHeader: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.gray100,
    backgroundColor: COLORS.white,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
  },
  pickerTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: COLORS.navy,
  },
  pickerDone: {
    fontSize: 16,
    fontWeight: 'bold',
    color: COLORS.gold,
  },
});
