import { StyleSheet } from 'react-native';
import { COLORS } from '../../constants/colors';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.offWhite },
  header: { backgroundColor: COLORS.navy, padding: 20, paddingTop: 56, flexDirection: 'row', alignItems: 'center', gap: 14 },
  backBtn: { padding: 4 },
  headerTitle: { fontSize: 20, fontWeight: 'bold', color: COLORS.white },
  image: { width: '100%', height: 200 },
  body: { padding: 20 },
  statusRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 },
  roomTitle: { fontSize: 20, fontWeight: 'bold', color: COLORS.navy, flex: 1, marginRight: 12 },
  badge: { paddingHorizontal: 12, paddingVertical: 5, borderRadius: 8 },
  confirmed: { backgroundColor: COLORS.greenLight },
  pending: { backgroundColor: COLORS.yellowLight },
  cancelled: { backgroundColor: COLORS.redLight },
  confirmedText: { color: COLORS.green, fontWeight: 'bold', fontSize: 13 },
  pendingText: { color: COLORS.yellow, fontWeight: 'bold', fontSize: 13 },
  cancelledText: { color: COLORS.red, fontWeight: 'bold', fontSize: 13 },
  card: { backgroundColor: COLORS.white, borderRadius: 14, padding: 16, marginBottom: 14, elevation: 2 },
  cardTitle: { fontSize: 13, fontWeight: 'bold', color: COLORS.gray400, letterSpacing: 0.5, marginBottom: 12 },
  row: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10 },
  rowLabel: { fontSize: 14, color: COLORS.gray500 },
  rowValue: { fontSize: 14, fontWeight: '600', color: COLORS.navy },
  divider: { height: 1, backgroundColor: COLORS.gray100, marginVertical: 10 },
  totalLabel: { fontSize: 15, fontWeight: 'bold', color: COLORS.navy },
  totalValue: { fontSize: 18, fontWeight: 'bold', color: COLORS.gold },
  feeNote: { fontSize: 12, color: COLORS.red, marginTop: 4, textAlign: 'right' },
  cancelBtn: { margin: 20, marginTop: 4, backgroundColor: COLORS.white, borderWidth: 1.5, borderColor: COLORS.red, borderRadius: 12, padding: 16, alignItems: 'center' },
  cancelBtnText: { color: COLORS.red, fontWeight: 'bold', fontSize: 16 },
  cancelledNote: { margin: 20, marginTop: 4, backgroundColor: COLORS.redLight, borderRadius: 12, padding: 14, alignItems: 'center' },
  cancelledNoteText: { color: COLORS.red, fontSize: 14, fontWeight: '500' },
  // Completed status
  completed: { backgroundColor: '#dbeafe' },
  completedText: { color: '#2563eb', fontWeight: 'bold', fontSize: 13 },
  // Action buttons
  rescheduleBtn: { margin: 20, marginBottom: 0, marginTop: 10, backgroundColor: COLORS.navy, borderRadius: 12, padding: 16, alignItems: 'center', shadowColor: COLORS.navy, shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.2, shadowRadius: 8, elevation: 4 },
  rescheduleBtnText: { color: COLORS.white, fontWeight: 'bold', fontSize: 16 },
  reviewBtn: { margin: 20, marginTop: 4, backgroundColor: COLORS.gold, borderRadius: 12, padding: 16, alignItems: 'center', shadowColor: COLORS.gold, shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.2, shadowRadius: 8, elevation: 4 },
  reviewBtnText: { color: COLORS.white, fontWeight: 'bold', fontSize: 16 },
  reviewedNote: { margin: 20, marginTop: 4, backgroundColor: COLORS.greenLight, borderRadius: 12, padding: 14, alignItems: 'center' },
  reviewedNoteText: { color: COLORS.green, fontSize: 14, fontWeight: '500' },
  // Shared modal
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,15,0.6)', justifyContent: 'flex-end' },
  modalSheet: { backgroundColor: COLORS.white, borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 24, paddingBottom: 40 },
  modalTitle: { fontSize: 20, fontWeight: 'bold', color: COLORS.navy, marginBottom: 24, textAlign: 'center' },
  modalLabel: { fontSize: 12, color: COLORS.gray500, marginBottom: 8, fontWeight: 'bold', letterSpacing: 0.5 },
  modalInput: { borderWidth: 1, borderColor: COLORS.gray200, borderRadius: 12, padding: 14, color: COLORS.navy, fontSize: 15, height: 100, textAlignVertical: 'top', backgroundColor: COLORS.offWhite },
  modalInputError: { borderColor: COLORS.red },
  modalError: { color: COLORS.red, fontSize: 12, marginTop: 4, marginBottom: 4 },
  starsRow: { flexDirection: 'row', gap: 12, justifyContent: 'center', marginBottom: 8 },
  modalSaveBtn: { backgroundColor: COLORS.gold, borderRadius: 12, padding: 16, alignItems: 'center', marginTop: 24, shadowColor: COLORS.gold, shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.2, shadowRadius: 8, elevation: 4 },
  modalSaveBtnText: { color: COLORS.white, fontWeight: 'bold', fontSize: 16 },
  modalCancelBtn: { borderRadius: 12, padding: 14, alignItems: 'center', marginTop: 8 },
  modalCancelBtnText: { color: COLORS.gray500, fontWeight: '600', fontSize: 15 },
  dateRow2: { flexDirection: 'row', gap: 12, marginBottom: 12 },
  dateBox2: { borderWidth: 1.5, borderColor: COLORS.gray100, borderRadius: 12, padding: 14, backgroundColor: COLORS.white },
  dateLabel2: { fontSize: 10, color: COLORS.gray400, marginBottom: 4, fontWeight: 'bold' },
  dateValue2: { fontSize: 14, fontWeight: 'bold', color: COLORS.navy },
  datePlaceholder2: { fontSize: 14, color: COLORS.gray300 },
  // Edit Booking Additions
  guestSelector: { 
    flexDirection: 'row', 
    alignItems: 'center', 
    justifyContent: 'space-between', 
    backgroundColor: COLORS.white, 
    borderRadius: 12, 
    padding: 10,
    borderWidth: 1.5,
    borderColor: COLORS.gray100,
  },
  guestBtn: { 
    width: 40, 
    height: 40, 
    borderRadius: 10, 
    backgroundColor: COLORS.white, 
    alignItems: 'center', 
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: COLORS.gray200,
  },
  guestCountText: { fontSize: 16, fontWeight: 'bold', color: COLORS.navy },
  capacityText: { fontSize: 12, color: COLORS.gray400, marginTop: 6, textAlign: 'center' },
  previewCard: { 
    backgroundColor: COLORS.navy + '05', 
    borderRadius: 16, 
    padding: 16, 
    marginTop: 24,
    borderWidth: 1,
    borderColor: COLORS.navy + '10',
  },
  previewRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginVertical: 4 },
  previewLabel: { fontSize: 13, color: COLORS.gray500 },
  previewValue: { fontSize: 14, fontWeight: '600', color: COLORS.navy },
  previewTotalLabel: { fontSize: 14, fontWeight: 'bold', color: COLORS.navy, marginTop: 4 },
  previewTotalValue: { fontSize: 18, fontWeight: 'bold', color: COLORS.gold },
  // Picker Styles
  pickerOverlay: { 
    flex: 1, 
    justifyContent: 'flex-end', 
    backgroundColor: 'rgba(0,0,15,0.5)' 
  },
  pickerSheet: { 
    backgroundColor: COLORS.white, 
    borderTopLeftRadius: 24, 
    borderTopRightRadius: 24, 
    paddingBottom: 40, 
    alignItems: 'center' 
  },
  pickerHeader: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.gray100,
    backgroundColor: COLORS.white,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
  },
  pickerTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: COLORS.navy,
  },
  pickerDone: {
    fontSize: 16,
    fontWeight: 'bold',
    color: COLORS.gold,
  },
});